
package uasoop;
import static.uasoop.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lab E
 */
public class bread_db extends javax.swing.JFrame {
    DefaultTableModel DTR = new DefaultTableModel();

    /**
     * Creates new form bread_db
     */
    public bread_db() throws SQLException {
        initComponents();
        tblroti.setModel(DTR);
        DTR.addColumn("ID");
        DTR.addColumn("Nama");
        DTR.addColumn("Jenis");
        DTR.addColumn("Harga");
        
        lsdtmhs();
        clearform();
        tombol(false);
        CTAMBAH.setEnabled(true);
        CSIMPAN.setEnabled(true);
        fieldAktif(false);
        
    }
    private void tombol(boolean opsi){
        CTAMBAH.setEnabled(opsi);
        CUBAH.setEnabled(opsi);
        CHAPUS.setEnabled(opsi);
        CSIMPAN.setEnabled(opsi);
        
    }
    
    private void fieldAktif(boolean opsi){
        txID.setEnabled(opsi);
        txNAMA.setEnabled(opsi);
        txJENIS.setEnabled(opsi);
        txHARGA.setEnabled(opsi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblroti = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txNAMA = new javax.swing.JTextField();
        txJENIS = new javax.swing.JTextField();
        txHARGA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CUBAH = new javax.swing.JButton();
        CHAPUS = new javax.swing.JButton();
        CTAMBAH = new javax.swing.JButton();
        CSIMPAN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblroti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblroti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblrotiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblroti);

        jLabel1.setText("DATA bread_db");

        txID.setText("jTextField1");

        jLabel2.setText("ID");

        txNAMA.setText("jTextField2");

        txJENIS.setText("jTextField3");

        txHARGA.setText("jTextField4");

        jLabel3.setText("Nama");

        jLabel4.setText("Jenis");

        jLabel5.setText("Harga");

        CUBAH.setText("UBAH");
        CUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUBAHActionPerformed(evt);
            }
        });

        CHAPUS.setText("HAPUS");
        CHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHAPUSActionPerformed(evt);
            }
        });

        CTAMBAH.setText("TAMBAH");
        CTAMBAH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CTAMBAHMouseClicked(evt);
            }
        });
        CTAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTAMBAHActionPerformed(evt);
            }
        });

        CSIMPAN.setText("SIMPAN");
        CSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSIMPANActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(txID, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                .addComponent(txNAMA)
                                .addComponent(txJENIS))
                            .addComponent(txHARGA, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CUBAH)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CSIMPAN)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CHAPUS)
                                        .addGap(18, 18, 18)
                                        .addComponent(CTAMBAH))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txJENIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txHARGA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CUBAH)
                            .addComponent(CHAPUS)
                            .addComponent(CTAMBAH))
                        .addGap(68, 68, 68)
                        .addComponent(CSIMPAN)))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CTAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTAMBAHActionPerformed
if(CTAMBAH.getText().equals("TAMBAH")){
        clearform();
        fieldAktif(true);    
        txJENIS.setVisible(true);
        CTAMBAH.setText("TAMBAH");
        CSIMPAN.setText("SIMPAN");
        CUBAH.setEnabled(true);
        CHAPUS.setEnabled(true);
        }else{
            try {
                storeData();
                lsdtmhs();
            } catch (SQLException ex) {
                Logger.getLogger(bread_db.class.getName()).log(Level.SEVERE, null, ex);
            }
        CTAMBAH.setText("TAMBAH");
        CSIMPAN.setText("SIMPAN");
        clearform();
        fieldAktif(false);
        txJENIS.setVisible(true);
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CTAMBAHActionPerformed

    private void CTAMBAHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTAMBAHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CTAMBAHMouseClicked

    private void CHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHAPUSActionPerformed
int opsi = JOptionPane.showOptionDialog(this, "Yakin akan menghapus Data "+txID.getText() +" ?", "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(opsi==JOptionPane.YES_NO_OPTION){
          try {
              destroyData();
              lsdtmhs();
              clearform();
              CHAPUS.setEnabled(true);
              CUBAH.setEnabled(true);
              
             
          } catch (SQLException ex) {
              Logger.getLogger(bread_db.class.getName()).log(Level.SEVERE, null, ex);
              
          }
            }        // TODO add your handling code here:
    }//GEN-LAST:event_CHAPUSActionPerformed

    private void CUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUBAHActionPerformed
        if(CUBAH.getText().equals("UBAH")){
        CUBAH.setText("UBAH");
        CSIMPAN.setText("SIMPAN");
        CTAMBAH.setEnabled(false);
        CHAPUS.setEnabled(false);
        fieldAktif(true);
        txID.setEditable(false);
        txNAMA.setVisible(false);
        
        }else{
            try{
                updateData();
                lsdtmhs();
            } catch (SQLException ex) {
                Logger.getLogger(bread_db.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        CUBAH.setText("UBAH");
        CSIMPAN.setText("SIMPAN");
        CTAMBAH.setEnabled(true);
        CUBAH.setEnabled(false);
        fieldAktif(false);
        clearform();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CUBAHActionPerformed

    private void CSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSIMPANActionPerformed
        if (CSIMPAN.getText().equals("SIMPAN") ){
            
            int opsi = JOptionPane.showOptionDialog(this, "Yakin akan menyimpan Data Aplikasi ?", "Konfirmasi Simpan Aplikasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(opsi==JOptionPane.YES_NO_OPTION){
            System.exit(0);
            }
            
        }else{
            CSIMPAN.setText("SIMPAN");
            CTAMBAH.setText("TAMBAH");
            CUBAH.setText("UBAH");
            CTAMBAH.setEnabled(true);
            CUBAH.setEnabled(false);
            txJENIS.setVisible(true);
            fieldAktif(false);
            clearform();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CSIMPANActionPerformed

    private void tblrotiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblrotiMouseClicked
        txID.setText( tblroti.getValueAt(tblroti.getSelectedRow(), 0).toString());
        txNAMA.setText( tblroti.getValueAt(tblroti.getSelectedRow(), 1).toString());
        txJENIS.setText( tblroti.getValueAt(tblroti.getSelectedRow(), 2).toString());
        txHARGA.setText( tblroti.getValueAt(tblroti.getSelectedRow(), 3).toString());
        
        CTAMBAH.setEnabled(true);
        CSIMPAN.setEnabled(true);
        
        
        
                // TODO add your handling code here:
    }//GEN-LAST:event_tblrotiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bread_db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bread_db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bread_db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bread_db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new bread_db().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(bread_db.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHAPUS;
    private javax.swing.JButton CSIMPAN;
    private javax.swing.JButton CTAMBAH;
    private javax.swing.JButton CUBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblroti;
    private javax.swing.JTextField txHARGA;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txJENIS;
    private javax.swing.JTextField txNAMA;
    // End of variables declaration//GEN-END:variables

  private void lsdtmhs() throws SQLException {
        Connection cnn = dbkoneksi.koneksi();
        
        DTR.getDataVector().removeAllElements();
        DTR.fireTableDataChanged();
        
        if( !cnn.isClosed()){
        
            PreparedStatement PS = cnn.prepareStatement("SELECT * FROM roti;");
            ResultSet RS = PS.executeQuery();
            while ( RS.next()){
                Object[] dtmhs = new Object[4];
                    dtmhs[0] = RS.getString("id_roti");
                    dtmhs[1] = RS.getString("nama_roti");
                    dtmhs[2] = RS.getString("jenis_roti");
                    dtmhs[3] = RS.getString("harga");


                    DTR.addRow(dtmhs);

            }      
        }
    }
  private void clearform(){
        txID.setText("");
        txNAMA.setText("");
        txJENIS.setText("");
        txHARGA.setText("");

  }
  
  private void storeData() throws SQLException {
       Connection cnn = dbkoneksi.koneksi();
       String ID = txID.getText();
       String Nama = txNAMA.getText();
       String Jenis = (txJENIS.getText() );
       String Harga = txHARGA.getText();
       
       if(!cnn.isClosed()){
           PreparedStatement PS = cnn.prepareStatement("INSERT INTO roti(id_roti,nama_roti,jenis_roti,harga) VALUES(?,?,?,?);");
           PS.setString(1, ID);
           PS.setString(2, Nama);
           PS.setString(3, Jenis);
           PS.setString(4, Harga);
           PS.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
           
       }
   
  }
  private void updateData() throws SQLException {
       Connection cnn = dbkoneksi.koneksi();
       String ID = txID.getText();
       String Nama = txNAMA.getText();
       String Jenis = txJENIS.getText() ;
       String Harga = txHARGA.getText();
       
       if(!cnn.isClosed()){
           PreparedStatement PS = cnn.prepareStatement("UPDATE roti SET nama_roti=?,jenis_roti=?,harga=? WHERE id_roti=?;");
           PS.setString(1, Nama);
           PS.setString(2, Jenis);
           PS.setString(3, Harga);
           PS.setString(4, ID);
           PS.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data berhasil diubah");
           
       }
    }
  private void destroyData() throws SQLException {
    Connection cnn = dbkoneksi.koneksi();
    String ID = txID.getText();
    
    if (!cnn.isClosed()) {
        PreparedStatement PS = cnn.prepareStatement("DELETE FROM roti WHERE id_roti=?;");
        PS.setString(1, ID);
        PS.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
    }
}

}
